### ISSUE TITLE
Run `deno test` with both husky pre-commit & GH action

### ISSUE THREAD

**Issue by sourishkrout** [stateful/runme.dev#29]
To detect when snapshots are updated.

**Comment by christian-bromann** [comment]
I modified the tests to not rely so heavily on snapshots all the time. Instead, it now checks if certain text components are rendered which is good enough.

**Comment by sourishkrout** [comment]
> I modified the tests to not rely so heavily on snapshots all the time. Instead, it now checks if certain text components are rendered which is good enough.

👍
