### ISSUE TITLE
Documentation section on runme.dev

### ISSUE THREAD

**Issue by admc** [stateful/runme.dev#44]
The runme project needs a proper home for documentation.

Some initial thoughts:
- mdx / docusauraus like webdriver.io looks like a good option
- they should probably live at /docs
- should be searchable
- should be search engine indexable (proper metadata)
- should be easy to distinguish between the extension and the CLI
- some initial pages could include: what our parser supports, how environment variables work, where commands are executed and how the shell works, configuration and how to stop runme from auto rendering markdown as runnable for example, more advanced integrations with services like vercel or deno deploy

Once we have a working documentation setup, it would make sense to expose the ones we think are most important in a docs section to replace the current "Cloud Service Integrations" on the front page, and a link in the nav.

After we have this wired up and are happy with it, we could do a design pass.

**Comment by admc** [comment]
@christian-bromann since you've done this before, it makes sense to have you lead the charge.

**Comment by christian-bromann** [comment]
Some questions to clairfy:

> * mdx / docusauraus

I assume we keep the same design though? Based on `we could do a design pass.` I assume yes, but wanted to confirm with you.

> * they should probably live at /docs

Can you confirm, that this means we eventually will archive this repository and move the docs into the `vscode-runme` repo.  Or would it be better within `stateful/runme`?

> * should be easy to distinguish between the extension and the CLI

Any suggestions for this one?

> * some initial pages could include

To scope for this effort, we will just port the current status quo and add docs sections and more content once we have a setup in place.

**Comment by admc** [comment]
Sounds like a conversation, good points - I don't have answers to that stuff. I put this on the kanban, so let's discuss when it gets prioritized.
