### ISSUE TITLE
Replace "Cloud Service Integrations" with "Documentation" section

### ISSUE THREAD

**Issue by admc** [stateful/runme.dev#47]
We want a section on the front page that show "popular" or "featured" docs sections, maybe just header / description for 4 or 6 sections. Not sure how to make this dynamic, but we want to make it feel more like a community oriented project.

If we can get the content there, we can do a design pass after that.

**Comment by christian-bromann** [comment]
@admc do you have an example for this?

**Comment by admc** [comment]
@christian-bromann Just made a comment in figma for you to check out

**Comment by christian-bromann** [comment]
Thanks! Do you have a specific content for these section in mind?

**Comment by admc** [comment]
Maybe we just update them to match:

- Link "Getting Started" to, "Install extension" -> renamed to "Install the extension", or maybe we actually make a getting started page where installing the extension is the first step? Not sure what other content we should have there.
- Configuration could become "Code Block Configuration" -> Linked to "Code Block Annotations" Or we could rename "Code Block Annotations" to "Configuration" and have annotations be a subset?
- "Contributing" -> Should probably be it's own section that reflects the content of a "contributing.md"?

Anyways, somehow make a lose mapping from docs related stuff we think folks are probably looking for, to whatever the closest section is in the docs we currently have, or create new stuff.

**Comment by christian-bromann** [comment]
Pushed a PR with an initial take on it. One thing I recognised is that all headings have a little drawings to it, this one doesn't, I will add a comment to Figma.
