### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by admc** [stateful/runme.dev#58]
We need a great getting started tutorial that gets users of all levels of experience to successfully use runme extension and CLI.

## Needs to cover:
1. Why would you want to use Runme?
2. Where to start
3. Common scenarios you'll encounter and what to do about them
4. When to configure cells versus when to edit your README to better leverage Runme
5. Known limitations and what we're planning to do about them
6. Various examples

Bonus points if you can bootstrap Runme with Runme.

## Scenarios (non-exhaustive):
- Run cell with a command it and it never stops because it's my dev watcher -> toggle background flag on in "Configure"
- Run cell but want output in notebook vs terminal -> if it's always non-interactive  -> toggle interactive flag off in "Configure"
- Run cell which fails because prerequisites are not met -> suggest to add cell at beginning with e.g. "apt install jq build-tools etc"
- ...

## Examples:
1. Get dev env up and running
2. Runbook-style workflow (load data into db; migrations; etc)
3. Document and issue API calls against server (curl, grpcurl, etc)
4. Simple `open https://...` deep linking to commonly used consoles (GCP, CMS, etc)
5. ...

Could probably also be a Stateful blog post.

**Comment by sourishkrout** [comment]
Here are all the drafts:

- Max: https://runme-dev-mxsdev.vercel.app/docs/getting-started/your-first-notebook
- Sebastian: https://runme-7ecqfluer-stateful.vercel.app/docs/intro
- Bencho: https://github.com/degrammer/runme-getting-started
- Adam: https://www.notion.so/statefulhq/Getting-Started-Runme-Adam-s-4c37680fc50b4e51822d80e3a92a05b5
- Christian: https://runme-8jh9rs1op-stateful.vercel.app/docs/getting-started

Should be able to provide raw-markdown for all of them if that's preferred.

**Comment by mxsdev** [comment]
Just pushed the source code for my guide onto `mxsdev/getting-started` if you all need the markdown/source there 👍
