### ISSUE TITLE
Sidebar broken on install docs

### ISSUE THREAD

**Issue by admc** [stateful/runme.dev#79]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/5144/218214576-2e7bd667-cfef-466c-bd58-20cafebc5feb.png">

**Comment by christian-bromann** [comment]
@admc can you provide more information how to reproduce this?

**Comment by admc** [comment]
- Open: https://runme.dev/docs/intro
- Click "Install Extension"

**Comment by christian-bromann** [comment]
I am unable to reproduce this anywhere, even tried some combinations in Sauce Labs. I also don't see DOM structure or classes differ from other pages. I am trying to find other folks that have a similar rendering bug until then there is nothing really I can do just yet.

**Comment by christian-bromann** [comment]
@admc found a way to reproduce it, can you check if #86 fixes the problem?
